### YamlMime:PythonClass
uid: azure.core.exceptions.ServiceRequestError
name: ServiceRequestError
fullName: azure.core.exceptions.ServiceRequestError
module: azure.core.exceptions
inheritances:
- azure.core.exceptions.AzureError
summary: 'An error occurred while attempt to make a request to the service.

  No request was sent.'
constructor:
  syntax: ServiceRequestError(message, *args, **kwargs)
  parameters:
  - name: message
methods:
- uid: azure.core.exceptions.ServiceRequestError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.exceptions.ServiceRequestError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    Deprecated since version 1.22.0: This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback()
- uid: azure.core.exceptions.ServiceRequestError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.exceptions.ServiceRequestError.args
  name: args
